services:
  db:
    image: postgres:14.1-alpine
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "user"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=foundher
      - POSTGRES_PASSWORD=pwd
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: foundher-backend
    build:
      context: ./backend
    image: backend
    depends_on:
      - db
    ports:
      - 8000:80
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local
